version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kuikbee_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: kuikbee_user
      POSTGRES_PASSWORD: kuikbee_pass
      POSTGRES_DB: kuikbee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: kuikbee_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data: